### ISSUE TITLE
Fautes d'orthographe 

### ISSUE THREAD

**Issue by mariegete** [peufo/trocio#41]
Salut, voici quelques corrections orthographiques à effectuer sur trocio :
**Sur la page d'accueil**
> éphémère --> éphémères 
> complette --> complète
> fluidifier --> fluidifiés
> Et éventuellement : tarifications --> tarification

**Sur la page de création d'un troc d'entrainement**
> visible --> visibles
> address --> adresse 
> d'entrainements --> d'entrainement

**Sur la page de création d'un troc**
> l'évenement --> l'évènement

**Comment by peufo** [comment]
Merci, 

C'est tout corrigé
