### ISSUE TITLE
risque de doublons sur numéro d'articles

### ISSUE THREAD

**Issue by garybaldi26** [peufo/trocio#43]
lors des propositions d'articles sur un troc d'entrainement de 2020 le numéro d'article reste figé sur 195, cela ne se produit pas si on charge une liste je n'ai pas tester sur un troc normal et récent

**Comment by peufo** [comment]
C'était du à un champ manquant sur ce vieux troc d'entrainement

**Comment by garybaldi26** [comment]
ok ca a l'air réglé
