### ISSUE TITLE
Exportation des listes d'articles par client

### ISSUE THREAD

**Issue by garybaldi26** [peufo/trocio#45]
au niveau du compte on peut télécharger 3 listes (propositions, achats, paiements) la liste "propositions" regroupe tous les articles proposés sans distinction de statut (proposé, validé, récupéré, vendu) peut on séparer ces listes?
surtout pour pouvoir télécharger la liste des invendus (validé et récupéré)

**Comment by peufo** [comment]
La nouvelle colonne "status" suffit elle ?

**Comment by garybaldi26** [comment]
oui effectivement cela peut suffire on filtre directement la liste dans Excel tu peux clôturer l'issue
