### ISSUE TITLE
Droits en modifications

### ISSUE THREAD

**Issue by garybaldi26** [peufo/trocio#46]
Revoir les droits d'éditions et modifications des articles au niveau d'un compte client pour les caissiers et les admins en fonctions des statuts de l'articles.
le prix et la désignation d'un article vendu ou récupéré ne doivent pas être modifiable.
le prix et la désignation d'un article proposé ou validé doit être modifiable via le compte client par le caissier.(traçabilité)

**Comment by peufo** [comment]
@garybaldi26  Ca doit être tout bon.
Tu peu confirmer ?

**Comment by garybaldi26** [comment]
ca joue test ok
